name: Android Debug CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # для тестового проекта не нужно
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      #  для тестового проекта не нужно
      # - name: Build Release APK
      #   run: ./gradlew assembleRelease

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        continue-on-error: true
        
      #  для тестового проекта не нужно
      # - name: Run Instrumented Tests
      #   run: ./gradlew connectedDebugAndroidTest
      #   continue-on-error: true

      #  для тестового проекта не нужно
      # - name: Static Code Analysis
      #   run: |
      #     ./gradlew ktlintCheck
      #     ./gradlew detekt

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/
          retention-days: 7

      #  для тестового проекта не нужно
      # - name: Upload Test Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-reports
      #     path: app/build/reports/
      #     retention-days: 7

      #  для тестового проекта не нужно
      # - name: Upload Lint Reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: lint-reports
      #     path: app/build/reports/lint/
      #     retention-days: 7
